launch=gmysql
gmysql-host=db
gmysql-user=pdns
gmysql-dbname=pdns
gmysql-password_file=/run/secrets/mysql_password
api=yes
api-key=/run/secrets/powerdns_api
webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
