launch=pgsql
pgsql-host=${PDNS_PGSQL_HOST}
pgsql-user=${PDNS_PGSQL_USER}
pgsql-password=$(cat /run/secrets/postgres_password)
pgsql-dbname=${PDNS_PGSQL_DBNAME}
api=yes
api-key=$(cat /run/secrets/pdns_api_key)
webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
